# MyoDishAnalysis (https://github.com/TS-IVS/MyoDishAnalysis)
# Copyright (c) 2026 Thomas Seidel
# SPDX-License-Identifier: GPL-3.0-or-later
# Additional terms (GPL-3.0 section 7): see the file NOTICE
"""Rows of the advanced settings window of the GUI and of the parameter tables of the settings guide (generated
from one parameter list, as advancedDefs in MyoDishAnalysisGUI.m).

ROWS: (option name, label, kind, popup items [(label, value)], description, scale (shown value = option value
x scale), unit, tab, reread (the data are read again)); kind: popup, check, num, int, numauto ('auto' or s),
vec (numbers). NEW: options added 2026-10-10 (before: constants in the code).

TS 2026-10-10
"""

TABS = ("Assignment", "Detection", "Noise / artifacts", "Rocker rules", "Signal", "Rocker filter", "Protocols", "Export")

ROWS = (
    ("stimAssignment", "Assignment", "popup", (("onset gate", "onset"), ("peak (<= 1.0.0-beta.3)", "peak")),
     "onset gate: a pulse can only have elicited a contraction if it lies from onset - gateMax to onset + "
     "gateTolerance (onset = tangent at the maximum dF/dt crossing the diastolic level). peak: last pulse "
     "minStimToPeak ... maxStimToPeak before the peak (versions <= 1.0.0-beta.3; extra pulses count as regular"
     " pulses)",
     1, "", "Assignment", False),
    ("gateMax", "gateMax: longest pulse -> onset delay", "num", None,
     "longest delay from the eliciting pulse to the contraction onset (Dmax). Near threshold the onset can be "
     "delayed by ~80 ms",
     1000, "ms", "Assignment", False),
    ("gateCore", "gateCore: typical delay range", "num", None,
     "several candidate pulses: pulses before the onset before pulses after it, regular before extra pulses; "
     "of one kind the earliest up to gateCore before the onset, otherwise the latest one",
     1000, "ms", "Assignment", False),
    ("gateTolerance", "gateTolerance: pulses after the onset", "num", None,
     "tolerance of the onset estimate (epsilon): pulses up to this time after the onset are still candidates; "
     "ambiguous if a pulse of the other kind would be chosen with the onset this time earlier or later",
     1000, "ms", "Assignment", False),
    ("ambiguityWindow", "ambiguityWindow", "num", None,
     "a pulse of the other kind (regular / extra) up to this time before or after the chosen pulse marks the "
     "assignment as ambiguous (column stimAmbiguous)",
     1000, "ms", "Assignment", False),
    ("risePhaseLevel", "risePhaseLevel: rise phases", "num", None,
     "no pulse in the gate of the onset: the onsets of the other rise phases of the upstroke are tried (local "
     "maxima of dF/dt of at least this fraction of the maximum dF/dt; rocker movement, fused spontaneous "
     "events)",
     100, "% of max dF/dt", "Assignment", False),
    ("steepRiseMargin", "steepRiseMargin", "num", None,
     "still no pulse: a pulse after the gate up to this time before the maximum dF/dt is taken (onset "
     "estimated too early, e.g. rocker artifacts); marked ambiguous",
     1000, "ms", "Assignment", False),
    ("contractionEnd", "contractionEnd: end of a contraction", "num", None,
     "end of a contraction for post-pulses, for regular pulses missed within a contraction and for the phase "
     "of the pulse table: this relaxation (% of peak - minimum after the peak)",
     1, "% relaxation", "Assignment", False),
    ("prePulseWindow", "prePulseWindow: pre-pulses kept", "num", None,
     "pulses without own contraction are listed as pre-pulses of the next contraction if they lie at most this"
     " time before its eliciting pulse (column prePulses); during a contraction (eliciting pulse ... "
     "contractionEnd) as post-pulses",
     1, "s", "Assignment", False),
    ("offsetSnap", "offsetSnap: programmed offsets", "num", None,
     "time of pre- / post-pulses: the programmed offset of the log file ('Sequence' entries) is used if the "
     "measured offset (resolution 2.5 ms) lies within this time of it",
     1000, "ms", "Assignment", False),
    ("minStimToPeak", "minStimToPeak (peak assignment)", "num", None,
     "peak assignment: a peak earlier than this after a pulse is not caused by it; onset gate: only for "
     "contractions without upstroke in the data",
     1000, "ms", "Assignment", False),
    ("maxStimToPeak", "maxStimToPeak (peak assignment)", "numauto", None,
     "peak assignment: auto = min(stimulus interval, 1 s), or a number of seconds",
     1, "s", "Assignment", False),
    ("externalTrigger", "Stimuli", "popup",
     (("auto", "auto"), ("MyoDish pulses", "off"), ("external trigger pulses", "on")),
     "stimulus times: MyoDish pulses of the channel, or the external trigger pulses of the status channel "
     "(external stimulator at the external controller unit: one chamber, any data channel). auto = external "
     "trigger pulses if the window has no MyoDish pulses",
     1, "", "Assignment", False),
    ("relThreshold", "relThreshold (auto threshold)", "num", None,
     "auto threshold: minimum prominence = this fraction of the typical contraction amplitude",
     1, "x typical", "Detection", False),
    ("minThreshold", "minThreshold (auto threshold)", "num", None,
     "auto threshold: never lower than this",
     1, "uN", "Detection", False),
    ("minBeatInterval", "minBeatInterval", "num", None,
     "minimum time between two contraction peaks (the more prominent one wins)",
     1, "s", "Detection", False),
    ("maxBeatWindow", "maxBeatWindow", "num", None,
     "at most this time before and after a peak belongs to one contraction (diastolic minimum, relaxation)",
     1, "s", "Detection", False),
    ("pacedMinStimuli", "pacedMinStimuli", "int", None,
     "a channel counts as paced with at least this many regular pulses in the data window: typical amplitude ="
     " median of the largest peaks (as many as pulses), noise level before the stimuli, rocker rules, "
     "certainty by locking; otherwise: largest gap between the sorted prominences",
     1, "pulses", "Detection", False),
    ("pauseMinInterval", "pauseMinInterval", "num", None,
     "stimulation pause: stimulus interval at least this long ...",
     1, "s", "Detection", False),
    ("pauseIntervalRatio", "pauseIntervalRatio", "num", None,
     "... and at least this multiple of the interval before; then F_dia is searched only from "
     "pauseDiastoleWindow before the stimulus",
     1, "x interval before", "Detection", False),
    ("pauseDiastoleWindow", "pauseDiastoleWindow", "num", None,
     "after a stimulation pause, the diastolic minimum is searched only from this time before the stimulus "
     "(inf = off)",
     1, "s", "Detection", False),
    ("diastolicLevel", "Diastolic level (F_dia)", "popup",
     (("median before the pulse", "preStimulusMedian"), ("minimum before the peak (<= 1.0.0-beta.3)", "minimum")),
     "level from which amplitude, upstroke levels (10 / 50 / 90 %), AUC and diastolic force are measured. "
     "median before the pulse: median of the unfiltered signal diastoleWindowStart ... diastoleWindowEnd "
     "before the eliciting pulse (contractions without pulse, or a median above the peak: minimum); minimum: "
     "last minimum of the filtered signal before the peak (versions <= 1.0.0-beta.3). Relaxation levels: "
     "minimum after the peak (both)",
     1, "", "Detection", False),
    ("diastoleWindowStart", "diastoleWindowStart: before the pulse", "num", None,
     "diastolic level 'median before the pulse': window from this time before the eliciting pulse ...",
     1000, "ms", "Detection", False),
    ("diastoleWindowEnd", "diastoleWindowEnd: before the pulse", "num", None,
     "... to this time before the pulse (stimulus artifact excluded)",
     1000, "ms", "Detection", False),
    ("lockWindow", "lockWindow: stimulus locking", "num", None,
     "a peak is locked to the stimuli if its latency (time since the previous pulse) lies within +-lockWindow "
     "of the typical latency (centre of the densest window of 2 x lockWindow); certainty and rocker / artifact"
     " rules",
     1000, "ms", "Detection", False),
    ("lockWindowRel", "lockWindowRel", "num", None,
     "at high rates the lock window is at most this fraction of the stimulus interval (certainty; rocker-only rule)",
     1, "x stimulus interval", "Detection", False),
    ("certainNoiseRel", "certainNoiseRel", "num", None,
     "certainty, paced: a locked contraction is certain if its prominence is >= this multiple of the median "
     "rise of the signal before the stimuli",
     1, "x median rise", "Detection", False),
    ("certainLargeRel", "certainLargeRel", "num", None,
     "certainty, paced: a contraction that is not locked is certain if it is >= this fraction of the typical "
     "amplitude ...",
     1, "x typical", "Detection", False),
    ("certainLargeNoiseRel", "certainLargeNoiseRel", "num", None,
     "... and >= this multiple of the median rise before the stimuli",
     1, "x median rise", "Detection", False),
    ("certainUnpacedRel", "certainUnpacedRel", "num", None,
     "certainty, unpaced channels: certain if >= this fraction of the typical amplitude",
     1, "x typical", "Detection", False),
    ("rockerArtifacts", "Rocker artifact rules", "check", None,
     "paced channels, auto threshold: peaks of the rocker movement that are not locked to the stimuli are not "
     "counted (artifact gap and rocker rules)",
     1, "", "Noise / artifacts", False),
    ("noiseMinInterval", "noiseMinInterval", "num", None,
     "noise level N: only windows before stimuli that follow an interval of at least this length",
     1, "s", "Noise / artifacts", False),
    ("noiseWindow", "noiseWindow", "num", None,
     "noise level N: window before each such stimulus (at most noiseWindowRel x interval); rise = maximum "
     "minus the running minimum of the signal",
     1, "s", "Noise / artifacts", False),
    ("noiseWindowRel", "noiseWindowRel", "num", None,
     "noise window at most this fraction of the stimulus interval",
     1, "x interval", "Noise / artifacts", False),
    ("noisePercentile", "noisePercentile", "num", None,
     "noise level N = this percentile of the rises (the median of the rises is used for the certainty)",
     1, "%", "Noise / artifacts", False),
    ("noiseMinWindows", "noiseMinWindows", "int", None,
     "noise level only with at least this many windows (otherwise unknown)",
     1, "windows", "Noise / artifacts", False),
    ("artifactMinCandidates", "artifactMinCandidates", "int", None,
     "artifact gap rule (raises the threshold): needs at least this many peaks above the auto threshold",
     1, "peaks", "Noise / artifacts", False),
    ("artifactGapRatio", "artifactGapRatio", "num", None,
     "artifact gap rule: the largest ratio between two consecutive sorted prominences below the typical "
     "amplitude must be >= this value (a clear gap between artifacts and contractions)",
     1, "x", "Noise / artifacts", False),
    ("artifactMaxRel", "artifactMaxRel", "num", None,
     "artifact gap rule: all peaks of the lower cluster are <= this fraction of the typical amplitude",
     1, "x typical", "Noise / artifacts", False),
    ("artifactMinPeaks", "artifactMinPeaks", "int", None,
     "artifact gap rule: at least this many peaks of the lower cluster are not locked to the stimuli",
     1, "peaks", "Noise / artifacts", False),
    ("artifactRockerFraction", "artifactRockerFraction", "num", None,
     "artifact gap rule: at least this fraction of the lower cluster occurs while the rocker moves",
     100, "%", "Noise / artifacts", False),
    ("chanceMargin", "chanceMargin", "num", None,
     "locked 'more than by chance': fraction locked > chance level (2 x lockWindow / stimulus interval) + this"
     " margin ...",
     100, "%", "Noise / artifacts", False),
    ("chanceMax", "chanceMax", "num", None,
     "... the limit is at most this fraction (artifact gap rule, partial capture of the rocker rules)",
     100, "%", "Noise / artifacts", False),
    ("rockerRuleMinFraction", "rockerRuleMinFraction", "num", None,
     "rocker rules (b, c): only if the rocker moves during at least this fraction of the data window",
     100, "% of the time", "Rocker rules", False),
    ("noiseLockedMax", "noiseLockedMax", "num", None,
     "rule b (no contractions): fewer than this fraction of the largest peaks (as many as pulses) locked ...",
     100, "%", "Rocker rules", False),
    ("noiseAbsMax", "noiseAbsMax", "num", None,
     "... and the typical amplitude <= this value ...",
     1, "uN", "Rocker rules", False),
    ("noiseRelMax", "noiseRelMax", "num", None,
     "... or <= this multiple of the noise level N with the peaks at the rhythm of the rocker: rocker / noise peaks",
     1, "x N", "Rocker rules", False),
    ("rhythmMinPerCycle", "rhythmMinPerCycle", "num", None,
     "rhythm of the rocker: at least this many peaks per rocker cycle (rule b) ...",
     1, "peaks / cycle", "Rocker rules", False),
    ("rhythmMaxPerCycle", "rhythmMaxPerCycle", "num", None,
     "... and at most this many, or a median peak interval of 1 or 1/2 rocker period ...",
     1, "peaks / cycle", "Rocker rules", False),
    ("rhythmTolerance", "rhythmTolerance", "num", None,
     "... within this tolerance (1/2 period: half of it)",
     100, "% of the period", "Rocker rules", False),
    ("keepNoiseRel", "keepNoiseRel", "num", None,
     "rule b: locked peaks >= max(keepNoiseRel x N, N + keepNoiseAbs) stay (slices that answer only some "
     "stimuli) ...",
     1, "x N", "Rocker rules", False),
    ("keepNoiseAbs", "keepNoiseAbs", "num", None,
     "... (absolute distance from the noise level) ...",
     1, "uN", "Rocker rules", False),
    ("keepMinPeaks", "keepMinPeaks", "int", None,
     "... if there are at least this many of them ...",
     1, "peaks", "Rocker rules", False),
    ("keepMinFraction", "keepMinFraction", "num", None,
     "... and at least this fraction of the pulses, and more of them are locked than by chance",
     100, "% of the pulses", "Rocker rules", False),
    ("dropRel", "dropRel", "num", None,
     "rule b: peaks below this multiple of max(typical amplitude, N) are removed (larger peaks are no rocker "
     "artifacts)",
     1, "x max(typical, N)", "Rocker rules", False),
    ("smallNoiseRel", "smallNoiseRel", "num", None,
     "rule c: peaks not locked to the stimuli below min(smallNoiseRel x N, smallTypicalRel x typical) are "
     "removed ...",
     1, "x N", "Rocker rules", False),
    ("smallTypicalRel", "smallTypicalRel", "num", None,
     "... (peaks at the rhythm of the rocker: smallRhythmTypicalRel instead) ...",
     1, "x typical", "Rocker rules", False),
    ("smallRhythmMinPerCycle", "smallRhythmMinPerCycle", "num", None,
     "... rhythm of the rocker for rule c: at least this many peaks per rocker cycle ...",
     1, "peaks / cycle", "Rocker rules", False),
    ("smallRhythmTypicalRel", "smallRhythmTypicalRel", "num", None,
     "... then the limit is min(smallNoiseRel x N, this fraction of the typical amplitude)",
     1, "x typical", "Rocker rules", False),
    ("rockerOnlyMinIntervals", "rockerOnlyMinIntervals", "int", None,
     "N unknown (high rates): peaks at the rhythm of the rocker need at least this many peak intervals ...",
     1, "intervals", "Rocker rules", False),
    ("rockerOnlyFraction", "rockerOnlyFraction", "num", None,
     "... of which at least this fraction are 1 or 1/2 rocker period ...",
     100, "%", "Rocker rules", False),
    ("rockerOnlyTolerance", "rockerOnlyTolerance", "num", None,
     "... within this tolerance (1/2 period: half of it) ...",
     100, "% of the period", "Rocker rules", False),
    ("captureTolerance", "captureTolerance", "num", None,
     "... and the median interval is no 1:1 or 2:1 multiple of the stimulus interval within this tolerance "
     "(capture at the rocker period cannot be told apart)",
     100, "%", "Rocker rules", False),
    ("downsampling", "downsampling (raw samples per value)", "int", None,
     "n raw samples are combined (2: mean, 400 Hz -> 200 Hz; n > 2: median); the window is read again",
     1, "samples", "Signal", True),
    ("medianFilterMs", "Moving median", "num", None,
     "moving median of the force signal (0 = off)",
     1, "ms", "Signal", False),
    ("meanFilterMs", "Moving mean", "num", None,
     "moving mean after the median (0 = off)",
     1, "ms", "Signal", False),
    ("spikeRemoval", "Remove spike artifacts", "check", None,
     "spike artifacts (e.g. chambers taken out / put in) are replaced by a line before the averaging of the "
     "raw samples (the window is read again)",
     1, "", "Signal", True),
    ("spikeJumpMin", "spikeJumpMin", "num", None,
     "spike: a jump between two raw samples >= J = max(spikeJumpMin, spikeJumpFactor x median of the non-zero "
     "differences of the channel) ...",
     1, "AU", "Signal", True),
    ("spikeJumpFactor", "spikeJumpFactor", "num", None,
     "... (noise level of the channel) ...",
     1, "x noise", "Signal", True),
    ("spikeGroupGap", "spikeGroupGap", "num", None,
     "jumps closer than this form one group ...",
     1000, "ms", "Signal", True),
    ("spikeMaxDuration", "spikeMaxDuration", "num", None,
     "... that lasts at most this long ...",
     1000, "ms", "Signal", True),
    ("spikeLevelWindow", "spikeLevelWindow", "num", None,
     "... and goes beyond the level before and after it (median of this time) by >= J ...",
     1000, "ms", "Signal", True),
    ("spikeJumpFraction", "spikeJumpFraction", "num", None,
     "... with the largest jump >= this fraction of its largest deviation (abrupt; a contraction rises over "
     "many samples)",
     100, "%", "Signal", True),
    ("spikeCoincidence", "spikeCoincidence", "num", None,
     "within this time of a spike of another channel ...",
     1000, "ms", "Signal", True),
    ("spikeCoincidenceFactor", "spikeCoincidenceFactor", "num", None,
     "... the jump threshold is max(spikeJumpMin, this factor x J) (spikes in several channels)",
     1, "x J", "Signal", True),
    ("rockerSource", "Rocker state from", "popup",
     (("auto", "auto"), ("status channel", "status"), ("log file", "log")),
     "auto: bit 15 of the status channel; the 'rockerSpeed' entries of the log file if that bit is missing or "
     "there is no status channel; the file is read again",
     1, "", "Rocker filter", True),
    ("rockerLogDelay", "rockerLogDelay", "num", None,
     "delay of the rocker movement after a 'rockerSpeed' entry of the log file (rocker state from the log file)",
     1, "s", "Rocker filter", True),
    ("rockerHzPerRpm", "rockerHzPerRpm", "num", None,
     "rocker frequency per rpm setting (two setups: 0.02020 and 0.02025 Hz/rpm); rocker rules and rocker filter",
     1, "Hz / rpm", "Rocker filter", False),
    ("rfBandRel", "rfBandRel: frequency search", "num", None,
     "rocker filter: the rocker frequency is searched within +-this fraction of the expected frequency",
     100, "%", "Rocker filter", False),
    ("rfBandNoLog", "rfBandNoLog", "vec", None,
     "rocker filter: search band without rocker speed in the log file",
     1, "Hz (from to)", "Rocker filter", False),
    ("rfHarmonics", "rfHarmonics", "int", None,
     "rocker filter: number of harmonics of the periodic artifact",
     1, "harmonics", "Rocker filter", False),
    ("rfBlock", "rfBlock", "num", None,
     "rocker filter: block length of the fit (hop = half a block)",
     1, "s", "Rocker filter", False),
    ("rfMinRun", "rfMinRun", "num", None,
     "rocker filter: shorter rocker-on periods are not corrected",
     1, "s", "Rocker filter", False),
    ("rfKnot", "rfKnot", "num", None,
     "rocker filter: knot distance of the baseline (slow drift) fitted together with the artifact",
     1, "s", "Rocker filter", False),
    ("rfSmoothBaseline", "rfSmoothBaseline", "num", None,
     "rocker filter: smoothness penalty of the baseline",
     1, "", "Rocker filter", False),
    ("rfRidge", "rfRidge", "num", None,
     "rocker filter: ridge penalty of the harmonics",
     1, "", "Rocker filter", False),
    ("rfMinCover", "rfMinCover", "num", None,
     "rocker filter: a block is fitted only if this fraction of the 20 phase bins of the rocker cycle has >= 5"
     " samples between the contractions",
     100, "%", "Rocker filter", False),
    ("rfMinR2", "rfMinR2", "num", None,
     "rocker filter: minimum R2 of a block fit",
     1, "", "Rocker filter", False),
    ("rfMaxSizeRel", "rfMaxSizeRel", "num", None,
     "rocker filter: artifact size of a block at most this multiple of the reference size",
     1, "x reference", "Rocker filter", False),
    ("rfMinRefBlock", "rfMinRefBlock", "num", None,
     "rocker filter: reference blocks are at least this long",
     1, "s", "Rocker filter", False),
    ("rfMaxBorrow", "rfMaxBorrow", "num", None,
     "rocker filter: a block without own fit uses the artifact of a neighbouring block of the same rocker "
     "period up to this distance",
     1, "s", "Rocker filter", False),
    ("rfF0Block", "rfF0Block", "num", None,
     "rocker filter, frequency estimate: blocks of at most this length ...",
     1, "s", "Rocker filter", False),
    ("rfF0Blocks", "rfF0Blocks", "int", None,
     "... at most this many per channel and rocker speed ...",
     1, "blocks", "Rocker filter", False),
    ("rfF0Clear", "rfF0Clear", "num", None,
     "... and the peak of the fit must be clear within +-this fraction",
     100, "%", "Rocker filter", False),
    ("rfExtendBlock", "rfExtendBlock", "num", None,
     "rocker filter: blocks without full coverage of the rocker cycle are retried with this length",
     1, "s", "Rocker filter", False),
    ("rfMaskRelax", "rfMaskRelax: contraction masks", "num", None,
     "rocker filter: the artifact is fitted to the samples between contractions; a contraction is masked from "
     "TTP90 + rfMaskMargin before its peak to rfMaskRelax x TTR90 + rfMaskMargin after it (medians of the "
     "channel)",
     1, "x TTR90", "Rocker filter", False),
    ("rfMaskMargin", "rfMaskMargin", "num", None,
     "rocker filter: margin of the contraction masks before and after a contraction",
     1000, "ms", "Rocker filter", False),
    ("rfMaskMax", "rfMaskMax: paced masks", "num", None,
     "rocker filter, paced channels (first pass): masked from 20 ms before each pulse to min(next pulse - 50 "
     "ms, this time) after it",
     1, "s", "Rocker filter", False),
    ("frequencyResolution", "frequencyResolution: >= 1 Hz", "num", None,
     "grouping by pacing frequency (FFR): stimulus intervals within 2 % form a group, its frequency (1 / "
     "median interval) is rounded to this step at >= 1 Hz; groups with the same rounded frequency are one "
     "group (0.99, 1.0 and 1.001 Hz = 1 Hz). FFR results: the groups at 0.5, 1, 2 and 3 Hz",
     1, "Hz", "Protocols", False),
    ("frequencyResolutionLow", "frequencyResolutionLow: < 1 Hz", "num", None,
     "... below 1 Hz the frequency is rounded to this step (0.49 and 0.5 Hz = 0.5 Hz, 0.74 and 0.75 Hz = 0.75 Hz)",
     1, "Hz", "Protocols", False),
    ("pauseTolerance", "pauseTolerance: pause length", "num", None,
     "grouping by pause length (post-rest potentiation): pauses (stimulus interval - steady interval) within "
     "this fraction of the shortest pause of a set are one pause length (same group value and label, numbered "
     "#n); PRP15 / 30 / 60: mean of the pauses within this fraction of 15 / 30 / 60 s",
     100, "%", "Protocols", False),
    ("steadyStateBeats", "steadyStateBeats: FFR steps", "int", None,
     "FFR protocols: each pacing frequency is summarized from its steady state: the last this many "
     "contractions of the longest run of consecutive stimuli at this frequency (other runs, e.g. the basic "
     "pacing before and after the protocol, are not used), of its longest sequence of captured stimuli "
     "whose previous and next stimuli are captured, too (partial capture, e.g. 2:1, gives no steady "
     "state). 0 = all contractions of the frequency (versions <= 1.0.0-beta.3)",
     1, "contractions", "Protocols", False),
    ("ffrRockerFallback", "FFR: steps without rocker stop", "check", None,
     "FFR protocols with rocker 'stopped' (default of protocols): contractions with the rocker at rest are "
     "used (more accurate); a step without such contractions is summarized from the contractions with the "
     "rocker moving (note)",
     1, "", "Protocols", False),
    ("prpReference", "PRP reference", "popup",
     (("last beats before each pause", "preceding"), ("train before the first pause", "firstTrain"), ("all steady contractions (<= 1.0.0-beta.3)", "steady")),
     "post-rest potentiation: reference amplitude of each post-rest contraction. last beats before each pause:"
     " median of the last prpReferenceBeats contractions of the pacing before this pause (this pacing loads "
     "the SR); train before the first pause: mean of the contractions of the pacing before the first pause of "
     "the protocol; all steady contractions: mean of the steady group (versions <= 1.0.0-beta.3). Reference "
     "contractions independent of the rocker state",
     1, "", "Protocols", False),
    ("prpReferenceBeats", "prpReferenceBeats", "int", None,
     "PRP reference 'last beats before each pause': number of contractions before the pause (median)",
     1, "contractions", "Protocols", False),
    ("irregularCV", "irregularCV: irregular groups", "num", None,
     "a group (e.g. FFR step) is flagged irregular (summary column irregular) if the coefficient of variation "
     "of the amplitudes of its included contractions (population SD / mean, column amplitude_CV) exceeds this "
     "value: conduction block, alternans or extra beats",
     100, "%", "Protocols", False),
    ("minGroupBeats", "minGroupBeats: few contractions", "int", None,
     "FFR protocols: a note lists the frequencies summarized from fewer included contractions (0 = no note)",
     1, "contractions", "Protocols", False),
    ("pulseTable", "Pulse table", "check", None,
     "exports and All channels -> file: table of all stimulus pulses (sheet / file pulses: pulse ID, time, "
     "extra pulse, current, durations, outcome, role, contraction, phase)",
     1, "", "Export", False),
    ("pulseTextMax", "pulseTextMax", "int", None,
     "prePulses / postPulses: at most this many pulses (those nearest to the eliciting pulse), then '&+<number"
     " of the others>'",
     1, "pulses", "Export", False),
)

NAMES = tuple(r[0] for r in ROWS)
NEW = ("risePhaseLevel", "steepRiseMargin", "contractionEnd", "offsetSnap", "pacedMinStimuli", "pauseMinInterval",
       "pauseIntervalRatio", "diastoleWindowStart", "diastoleWindowEnd", "lockWindow", "lockWindowRel",
       "certainNoiseRel", "certainLargeRel", "certainLargeNoiseRel", "certainUnpacedRel", "noiseMinInterval",
       "noiseWindow", "noiseWindowRel", "noisePercentile", "noiseMinWindows", "artifactMinCandidates",
       "artifactGapRatio", "artifactMaxRel", "artifactMinPeaks", "artifactRockerFraction", "chanceMargin",
       "chanceMax", "rockerRuleMinFraction", "noiseLockedMax", "noiseAbsMax", "noiseRelMax", "rhythmMinPerCycle",
       "rhythmMaxPerCycle", "rhythmTolerance", "keepNoiseRel", "keepNoiseAbs", "keepMinPeaks", "keepMinFraction",
       "dropRel", "smallNoiseRel", "smallTypicalRel", "smallRhythmMinPerCycle", "smallRhythmTypicalRel",
       "rockerOnlyMinIntervals", "rockerOnlyFraction", "rockerOnlyTolerance", "captureTolerance", "spikeJumpMin",
       "spikeJumpFactor", "spikeGroupGap", "spikeMaxDuration", "spikeLevelWindow", "spikeJumpFraction",
       "spikeCoincidence", "spikeCoincidenceFactor", "rockerHzPerRpm", "rfBandRel", "rfBandNoLog", "rfHarmonics",
       "rfBlock", "rfMinRun", "rfKnot", "rfSmoothBaseline", "rfRidge", "rfMinCover", "rfMinR2", "rfMaxSizeRel",
       "rfMinRefBlock", "rfMaxBorrow", "rfF0Block", "rfF0Blocks", "rfF0Clear", "rfExtendBlock", "rfMaskRelax",
       "rfMaskMargin", "rfMaskMax", "frequencyResolution", "frequencyResolutionLow", "pauseTolerance",
       "steadyStateBeats", "prpReferenceBeats", "irregularCV", "minGroupBeats", "pulseTextMax")
